"""Packaged protocol/roster regression over loopback; does not prove EOS or WAN."""
import argparse, time
from net_harness import NetworkTest, Peer, host_url, wait_for, distance, BUILD

p=argparse.ArgumentParser()
p.add_argument('--executable', required=True)
p.add_argument('--output', default='Tests/Results/eos-qa-20260924/lobby')
a=p.parse_args()
t=NetworkTest(a.output, executable=a.executable)
try:
    host=Peer(t,'QAHost',host_url(2,bots=False))
    old=Peer(t,'QAOld',f'127.0.0.1:7788?DinoBuild={BUILD-1}')
    t.check('intentionally old travel build rejected',wait_for(lambda:old.state()['onlineStatus']=='Different game version.'),local=BUILD,remote=BUILD-1)
    t.check('rejected client never enters roster',len(host.state()['players'])==1)
    old.quit()
    missing=Peer(t,'QAMissing','127.0.0.1:7788')
    t.check('missing travel build rejected',wait_for(lambda:missing.state()['onlineStatus']=='Different game version.'))
    missing.quit()
    guest=Peer(t,'QAGuest')
    t.check('identical build enters two-player lobby',wait_for(lambda:len(host.state()['players'])==2 and len(guest.state()['players'])==2 and guest.state()['lobby']))
    t.check('host and guest report authoritative compatibility',host.state()['compatibilityBuild']==guest.state()['compatibilityBuild']==BUILD)
    t.check('bots remain off and capacity remains two',not host.state()['bots'] and guest.state()['capacity']==2)
    guest.lobby(0,1)
    t.check('guest dinosaur selection replicates',wait_for(lambda:host.player(1)['species']==1))
    host.lobby(6)
    t.check('unready guest prevents start',wait_for(lambda:'Ready' in host.state()['lobbyStatus']) and host.state()['lobby'])
    guest.lobby(2,1)
    t.check('guest ready replicates',wait_for(lambda:host.player(1)['ready']))
    host.lobby(6)
    t.check('both players enter match',wait_for(lambda:not guest.state()['lobby'] and not host.state()['lobby']))
    before=guest.state();after=guest.hold('W',.7)
    t.check('guest controls move in match',distance(before,after)>100,distance=distance(before,after))
    t.check('raptor followers replicate',wait_for(lambda:len([d for d in guest.state()['networkActors'] if d['follower'] and d['pack']==1])==2))
    host.lobby(7)
    t.check('host returns both to lobby',wait_for(lambda:guest.state()['lobby'] and host.state()['lobby']))
    guest.quit()
    t.check('guest departure cleans roster',wait_for(lambda:len(host.state()['players'])==1))
    host.quit()
finally:
    t.close()
