"""Stages D/E: real clients and server-owned scoring fixtures, then real friendly attacks."""
import time
from net_harness import NetworkTest,Peer,host_url,wait_for,distance
t=NetworkTest('Tests/Results/multiplayer/stage-de-01')
try:
    host=Peer(t,'MatchHost',host_url(6));client=Peer(t,'MatchClient');time.sleep(.5)
    client.lobby(2,1);host.lobby(6);host.command('ai',paused=True)
    t.check('two humans begin FFA with empty slots',wait_for(lambda:not client.state()['lobby']) and len([a for a in client.state()['networkActors'] if a['id']<100])==2)
    for count in range(1,6):
        if count>1:host.command('resetCombatant',id=1)
        host.command('scoreHit',attacker=0,victim=1,value=100000)
        t.check(f'FFA kill {count} replicated once',wait_for(lambda:client.actor(1)['dead'] and client.state()['scoreboard'][0]['kills']==count))
        if count<5:t.check(f'FFA continues below five ({count})',not client.state()['roundOver'])
    t.check('five-kill victory shared',wait_for(lambda:client.state()['roundOver'] and client.state()['winner']==0 and client.state()['menuOpen']))
    before=client.state();client.command('menu',open=False);after=client.hold('W',.4)
    t.check('results freeze client movement',distance(before,after)<5)
    host.lobby(8)
    t.check('host rematch resets scores and corpses',wait_for(lambda:not client.state()['roundOver'] and all(s['kills']==0 for s in client.state()['scoreboard']) and len(client.state()['corpses'])==0))
    t.check('rematch restores living players',not host.state()['dead'] and not client.state()['dead'])
    host.lobby(7);host.lobby(3,1)
    third=Peer(t,'MatchThird');time.sleep(.6)
    client.lobby(1,0);third.lobby(1,1);client.lobby(2,1);third.lobby(2,1);host.lobby(6)
    t.check('odd 2v1 team match starts',wait_for(lambda:not third.state()['lobby']) and sum(a['team']==0 for a in host.state()['players'])==2)
    host.command('ai',paused=True);host.command('teleport',x=0,y=0);host.command('face',yaw=0)
    host.command('testAI',id=1,species=0,x=450,y=0,yaw=180,health=1,enabled=False);time.sleep(.6)
    hp=client.state()['health'];host.tap('LeftMouseButton');time.sleep(.9)
    t.check('real quick attack ignores teammate',abs(client.state()['health']-hp)<.01)
    client.command('face',yaw=180);client.tap('LeftMouseButton');time.sleep(.9)
    t.check('client quick attack ignores allied host',host.state()['health']==host.state()['maxHealth'])
    for count in range(1,11):
        if count>1:host.command('resetCombatant',id=2)
        host.command('scoreHit',attacker=0,victim=2,value=1)
        host.command('scoreHit',attacker=1,victim=2,value=100000)
        t.check(f'team kill {count} replicated',wait_for(lambda:third.state()['team0Kills']==count))
        if count<10:t.check(f'team continues below ten ({count})',not third.state()['roundOver'])
    t.check('ten-kill team victory shared',wait_for(lambda:third.state()['roundOver'] and client.state()['roundOver'] and third.state()['winnerTeam']==0))
    t.check('assists are authoritative and replicated',wait_for(lambda:host.state()['assists']==10 and next(s for s in third.state()['scoreboard'] if s['id']==0)['assists']==10))
    t.check('individual kills tracked for client winner',client.state()['kills']==10 and third.state()['deaths']==10)
    for repeat in range(3):
        host.lobby(8)
        t.check(f'rematch {repeat+1} clears shared score and carcasses',wait_for(lambda:not third.state()['roundOver'] and third.state()['team0Kills']==0 and len(third.state()['corpses'])==0))
        t.check(f'rematch {repeat+1} has exactly three participants',len([a for a in host.state()['networkActors'] if a['id']<100])==3)
        host.lobby(7);client.lobby(2,1);third.lobby(2,1);host.lobby(6)
        t.check(f'lobby restart {repeat+1} succeeds',wait_for(lambda:not third.state()['lobby']))
    third.quit();client.quit();host.quit()
finally:t.close()
