"""Stage C: real server/client lobby state and permission boundaries."""
import time
from net_harness import NetworkTest,Peer,host_url,wait_for,distance
t=NetworkTest('Tests/Results/multiplayer/stage-c-02')
try:
    host=Peer(t,'LobbyHost',host_url(6));client=Peer(t,'LobbyClient');time.sleep(1)
    t.check('shared pre-match lobby',host.state()['lobby'] and client.state()['lobby'])
    t.check('capacity and connected players replicated',client.state()['capacity']==6 and len(client.state()['players'])==2)
    t.check('only host marked as host',client.player(0)['host'] and not client.player(1)['host'])
    before=client.state();client.command('menu',open=False);after=client.hold('W',.7)
    t.check('lobby prevents gameplay movement',distance(before,after)<10,distance=distance(before,after))
    client.lobby(0,2)
    t.check('guest chooses own species',wait_for(lambda:host.player(1)['species']==2 and client.state()['species']==2))
    client.lobby(4,10);client.lobby(3,1);client.lobby(6)
    time.sleep(.4);t.check('guest cannot change host settings or start',client.state()['capacity']==6 and not client.state()['teamMode'] and client.state()['lobby'])
    host.lobby(4,4);host.lobby(3,1)
    t.check('host settings synchronized',wait_for(lambda:client.state()['capacity']==4 and client.state()['teamMode']))
    t.check('teams assigned automatically',wait_for(lambda:{p['team'] for p in client.state()['players']}=={0,1}))
    client.lobby(1,0);t.check('guest changes own team',wait_for(lambda:host.player(1)['team']==0))
    client.lobby(1,-1);t.check('automatic team balances humans',wait_for(lambda:host.player(1)['team']==1))
    host.lobby(6);t.check('unready guest blocks start',wait_for(lambda:'Ready' in host.state()['lobbyStatus']) and host.state()['lobby'])
    client.lobby(2,1);t.check('ready state synchronized',wait_for(lambda:host.player(1)['ready']))
    host.lobby(6);t.check('host starts both players together',wait_for(lambda:not client.state()['lobby'] and not host.state()['lobby']))
    t.check('menus close after replicated start',wait_for(lambda:not client.state()['menuOpen'] and not host.state()['menuOpen']))
    host.command('ai',paused=True)
    a=client.state();b=client.hold('W',.6);t.check('client controls dinosaur after start',distance(a,b)>100,distance=distance(a,b))
    client.lobby(7);time.sleep(.3);t.check('guest cannot return everyone to lobby',not host.state()['lobby'])
    host.lobby(7);t.check('host returns both to lobby',wait_for(lambda:client.state()['lobby'] and client.state()['menuOpen']))
    t.check('lobby clears readiness',wait_for(lambda:not client.player(1)['ready']))
    t.check('no duplicate participants across lobby transition',len([a for a in client.state()['networkActors'] if a['id']<100])==2)
    client.quit();t.check('departed player removed from lobby',wait_for(lambda:len(host.state()['players'])==1))
    host.quit()
finally:t.close()
